# Generated by Django 4.1 on 2022-08-21 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                ("sibilings", models.IntegerField()),
                ("address", models.TextField(max_length=100)),
                ("parent_mobile", models.IntegerField()),
                ("date_of_joining", models.DateField()),
                (
                    "mode_of_stay",
                    models.CharField(
                        choices=[
                            ("Hosteller", "Hosteller"),
                            ("DayScholer", "DayScholer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fees", models.IntegerField()),
                (
                    "created_dtm",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_dtm", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
