# Generated by Django 4.1 on 2022-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_teacher_id",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
    ]
