# Generated by Django 4.1 on 2022-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_class_teacher_id_alter_student_father_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_teacher_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
