# Generated by Django 4.1 on 2022-08-23 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(max_length=100)),
                ("date_of_joining", models.DateField()),
                ("salary", models.IntegerField()),
                ("subject", models.CharField(max_length=10)),
                ("previous_organization", models.CharField(max_length=30)),
                (
                    "created_dtm",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_dtm", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher",
            },
        ),
    ]
